namespace: libretranslate
domain: hn.eaera.com
ingress:
  host: libretranslate.hn.eaera.com
storage:
  size: 32Gi
  storageClassName: openebs-hostpath
  # persistentVolume:
  #   enabled: true
  #   volumeHandle: /subscriptions/ca345c4a-2897-4c58-abce-a7598b1630cb/resourceGroups/MC_rg-eaera-sea_eaera-sea-2_southeastasia/providers/Microsoft.Compute/disks/LibreTranslateData
  dbNodeAffinity:
    - key: kubernetes.io/hostname
      operator: In
      value: hn-worker-3
tolerations:
- key: agentpool
  operator: Equal
  value: app
  effect: NoSchedule